# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0cinference.v1\"\xb6\x01\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\ninput_text\x18\x02 \x01(\t\x12\x13\n\x0binput_image\x18\x03 \x01(\x0c\x12\x38\n\x06params\x18\x04 \x03(\x0b\x32(.inference.v1.PredictRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"L\n\x0fPredictResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x02\x12\x15\n\rmodel_version\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x9f\x01\n\x10InferenceService\x12\x46\n\x07Predict\x12\x1c.inference.v1.PredictRequest\x1a\x1d.inference.v1.PredictResponse\x12\x43\n\x06Health\x12\x1b.inference.v1.HealthRequest\x1a\x1c.inference.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=34
  _globals['_PREDICTREQUEST']._serialized_end=216
  _globals['_PREDICTREQUEST_PARAMSENTRY']._serialized_start=171
  _globals['_PREDICTREQUEST_PARAMSENTRY']._serialized_end=216
  _globals['_PREDICTRESPONSE']._serialized_start=218
  _globals['_PREDICTRESPONSE']._serialized_end=294
  _globals['_HEALTHREQUEST']._serialized_start=296
  _globals['_HEALTHREQUEST']._serialized_end=311
  _globals['_HEALTHRESPONSE']._serialized_start=313
  _globals['_HEALTHRESPONSE']._serialized_end=345
  _globals['_INFERENCESERVICE']._serialized_start=348
  _globals['_INFERENCESERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
